SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d'), PRODUCT_ID, USER_ID, SALES_AMOUNT FROM (SELECT * FROM ONLINE_SALE
UNION
SELECT offline_sale_id,
null,
product_id,
sales_amount,
sales_date FROM OFFLINE_SALE) meme
WHERE SALES_DATE LIKE '2022-03-%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

