--  즐겨찾기수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회

# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_INFO
# GROUP BY FOOD_TYPE
# having FAVORITES = max(FAVORITES)
# ORDER BY FOOD_TYPE desc

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_INFO
where (FOOD_TYPE, FAVORITES) in (select FOOD_TYPE, max(FAVORITES) from REST_INFO GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
order by FOOD_TYPE desc


