-- 코드를 입력하세요
SELECT FLAVOR FROM
(SELECT *, SUM(TOTAL_ORDER+JULY_TOTAL) RESULT FROM FIRST_HALF f
LEFT JOIN
(SELECT FLAVOR, sum(TOTAL_ORDER) JULY_TOTAL FROM JULY
GROUP BY FLAVOR) j
USING (FLAVOR)
GROUP BY FLAVOR
ORDER BY RESULT DESC) w
LIMIT 3